spring.application.name=financas-backend

# Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gerenciador_financas
spring.datasource.username=postgres
spring.datasource.password=2208

# Configurações para o Java conversar com o Banco
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=financas-super-secret-key-2026-change-in-production
jwt.expiration=86400000
